-- Consolidated schema migration
-- Generated manually from Production Project: xlupnknqblvvlcfprghr

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";

-- 2. Enums
DO $$ BEGIN
    CREATE TYPE public."Propositos" AS ENUM ('Alimentação', 'Entretenimento', 'Mercado');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."categoria_proposito" AS ENUM ('Alimentação', 'Mercado', 'Minha reserva', 'Entretenimento');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."status" AS ENUM ('invited', 'active', 'blocked', 'inactive');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."tipo_contrato" AS ENUM ('Parcial', 'Full');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."tipo_periodos" AS ENUM ('Manhã', 'Tarde', 'Noite');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."tipo_transacao" AS ENUM ('Crédito', 'Débito', 'Transferência');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public."tipo_user" AS ENUM ('Admin', 'Escola', 'Lojista', 'Aluno', 'Responsavel', 'Convidado', 'Professor');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 3. Tables
CREATE TABLE IF NOT EXISTS public."escola" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "razao_social" varchar,
    "nome_fantasia" varchar,
    "cnpj" varchar UNIQUE,
    "email_contato" varchar,
    "telefone_contato" varchar,
    "whatsapp" varchar,
    "endereco" text,
    "responsavel_pedagogico" varchar,
    "responsavel_direcao" varchar,
    "tipo_escola" varchar,
    "ordenacao" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    "modelo_contratacao" varchar,
    "dias_repasse" integer,
    "possui_equipamentos" boolean DEFAULT false,
    "quantidade_equipamentos" integer DEFAULT 0,
    "valor_unitario_equipamento" numeric DEFAULT 0,
    "cobra_transacoes" boolean DEFAULT false,
    "valor_unitario_transacao" numeric DEFAULT 0,
    "valor_carteira" numeric DEFAULT 0,
    "valor_transferencia" numeric DEFAULT 0,
    "nome_secretariado" varchar,
    "email_secretaria_admin" varchar,
    "cep" varchar,
    "complemento" varchar,
    "status" public."status" DEFAULT 'active'::public.status,
    "deletado" boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public."turma" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "nome" varchar,
    "ano_semestre" varchar,
    "Periodos" varchar,
    "estagio" text,
    "serie" text,
    "professor" text,
    "quantidade_alunos" integer DEFAULT 0,
    "data_entrada" date DEFAULT CURRENT_DATE,
    "status" boolean DEFAULT true,
    "nome_filtro" varchar,
    "data_inicio" date DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS public."usuarios" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now(),
    "nome" varchar,
    "data_nascimento" date,
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "foto_perfil" text,
    "nome_completo" text,
    "nome_mae" text,
    "ra" varchar,
    "saldo_carteira" numeric DEFAULT 0.00,
    "saldo_investido" numeric DEFAULT 0.00,
    "temp_pass" text,
    "email" varchar,
    "UserID" uuid DEFAULT auth.uid(),
    "cpf" varchar,
    "turmaID" uuid REFERENCES public.turma(id) ON DELETE CASCADE,
    "tipo_acesso" public.tipo_user,
    "ultimo_login" date,
    "status" public.status DEFAULT 'active'::public.status,
    "senha" varchar,
    "deleted" boolean DEFAULT false,
    "Proposito_Lojista" public."Propositos",
    "total_vendas" numeric,
    "total_devolucao" numeric,
    "reset_code" text,
    "reset_expires_at" timestamp with time zone,
    "grau_escolaridade" text,
    "excluido" text DEFAULT 'no'::text
);

CREATE TABLE IF NOT EXISTS public."aluno" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "turma_id" uuid REFERENCES public.turma(id) ON DELETE CASCADE,
    "nome" varchar,
    "email" varchar,
    "cpf" varchar,
    "transfeera_recipient_id" varchar,
    "transfeera_status" varchar,
    "transfeera_key_type" varchar,
    "transfeera_key_value" varchar,
    "user_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "primeiro_acesso" boolean,
    "data_nascimento" date,
    "foto_perfil" text,
    "nome_completo" text,
    "nome_mae" text,
    "ra" varchar,
    "saldo_carteira" numeric DEFAULT 0.00,
    "saldo_investido" numeric DEFAULT 0.00,
    "temp_pass" text,
    "usuario_id" bigint REFERENCES public.usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."professor" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "nome" varchar,
    "especialidade" varchar
);

CREATE TABLE IF NOT EXISTS public."noticia" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "titulo" varchar,
    "conteudo" text,
    "data_publicacao" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."produto" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "nome" varchar,
    "descricao" text,
    "preco" numeric,
    "url_imagem" varchar,
    "Data_vigencia_incio" date,
    "Data_vigencia_final" date,
    "limete_por_aluno" numeric,
    "Status" boolean,
    "quantidade" integer DEFAULT 0,
    "turma_ids" uuid[] DEFAULT '{}'::uuid[]
);

CREATE TABLE IF NOT EXISTS public."investimento" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "nome" varchar,
    "descricao" text,
    "tipo" varchar
);

CREATE TABLE IF NOT EXISTS public."investimento_aluno" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "aluno_id" uuid REFERENCES public.aluno(id) ON DELETE CASCADE,
    "investimento_id" uuid REFERENCES public.investimento(id) ON DELETE CASCADE,
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "data_inicio" date,
    "data_resgate" date,
    "valor_investido" numeric DEFAULT 0,
    "saldo_atual" numeric DEFAULT 0,
    "quantidade_ativos" numeric,
    "rentabilidade_acumulada" numeric DEFAULT 0,
    "valor_resgate" numeric,
    "status_investimento" varchar DEFAULT 'Ativo'::character varying,
    "titulo" varchar,
    "created_date" timestamp with time zone DEFAULT now(),
    "descricao" text,
    "valor" numeric,
    "id_user" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "id_pix_transfeera" text
);

CREATE TABLE IF NOT EXISTS public."historico_investimento" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "investimento_aluno_id" uuid REFERENCES public.investimento_aluno(id) ON DELETE CASCADE,
    "data_transacao" timestamp with time zone DEFAULT now(),
    "tipo_operacao" varchar,
    "valor_movimento" numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public."log_valorizacao_dinamica" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "investimento_id" uuid REFERENCES public.investimento(id) ON DELETE CASCADE,
    "valor_aplicado" numeric,
    "sequencia" integer,
    "log_detalhes" text,
    "data_registro" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."aluno_inventario" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "aluno_id" uuid REFERENCES public.aluno(id) ON DELETE CASCADE,
    "produto_id" uuid REFERENCES public.produto(id) ON DELETE CASCADE,
    "nome_item" varchar,
    "descricao" text,
    "imagem_url" varchar,
    "data_aquisicao" timestamp with time zone DEFAULT now(),
    "data_expiracao" timestamp with time zone,
    "valor_aquisicao" numeric,
    "quantidade" integer DEFAULT 1,
    "status_item" varchar
);

CREATE TABLE IF NOT EXISTS public."missao" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "descricao" text,
    "data_inicio" timestamp with time zone,
    "data_termino" timestamp with time zone,
    "recompensa" text
);

CREATE TABLE IF NOT EXISTS public."logs_missao" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "missao_id" uuid REFERENCES public.missao(id) ON DELETE CASCADE,
    "aluno_id" uuid REFERENCES public.aluno(id) ON DELETE CASCADE,
    "log_texto" text,
    "data_log" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."transfeera_log" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "aluno_id" uuid REFERENCES public.aluno(id) ON DELETE CASCADE,
    "tipo_operacao" varchar,
    "endpoint_url" varchar,
    "request_payload" jsonb,
    "response_payload" jsonb,
    "http_status" integer,
    "external_id" varchar,
    "status" varchar,
    "created_date" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."propositos" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "nome" text NOT NULL,
    "saldo" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "usuario_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."whatsapp_instances" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "instance_name" text UNIQUE NOT NULL,
    "status" text DEFAULT 'disconnected'::text,
    "qrcode" text,
    "last_updated" timestamp with time zone DEFAULT now(),
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    "integration_config" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."whatsapp_messages" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "patient_name" text,
    "phone" text NOT NULL,
    "content" text,
    "status" text DEFAULT 'pending'::text,
    "error_message" text,
    "sent_at" timestamp with time zone DEFAULT now(),
    "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."Carteira" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now(),
    "Usuario" bigint REFERENCES public.usuarios(id) ON DELETE CASCADE,
    "carteira_code" varchar,
    "turmaID" uuid DEFAULT gen_random_uuid(),
    "escola_id" uuid DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS public."lojista_historico" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "lojista_id" uuid,
    "aluno_id" uuid,
    "aluno_nome" text,
    "aluno_turma" text,
    "valor" numeric NOT NULL,
    "tipo_operacao" text CHECK (tipo_operacao = ANY (ARRAY['VENDA'::text, 'DEVOLUCAO'::text, 'RETIRADA'::text, 'REPOSICAO'::text])),
    "saldo_vendas_pos" numeric,
    "data_hora" timestamp with time zone DEFAULT now(),
    "descricao" text
);

CREATE TABLE IF NOT EXISTS public."pedidos_compra" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "numero" text NOT NULL,
    "ong_id" uuid NOT NULL,
    "data_solicitacao" timestamp with time zone DEFAULT now(),
    "prioridade" text DEFAULT 'Normal'::text,
    "status" text DEFAULT 'Pendente'::text,
    "solicitante" text,
    "fornecedor_sugerido" text,
    "observacao" text,
    "deletado" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."pedidos_compra_itens" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "pedido_id" uuid REFERENCES public.pedidos_compra(id) ON DELETE CASCADE,
    "produto_id" uuid,
    "nome_produto" text NOT NULL,
    "quantidade_solicitada" numeric DEFAULT 0,
    "unidade_medida" text DEFAULT 'UN'::text,
    "estoque_atual" numeric DEFAULT 0,
    "estoque_minimo" numeric DEFAULT 0,
    "sugestao_compra" numeric DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."eventos" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "escola_id" uuid REFERENCES public.escola(id) ON DELETE CASCADE,
    "capa_url" text,
    "ativo" boolean DEFAULT false,
    "nome" text NOT NULL,
    "descricao_curta" text,
    "data_evento" date,
    "lojistas_convidados" text[],
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "turma_id" uuid REFERENCES public.turma(id) ON DELETE CASCADE,
    "turma_ids" uuid[]
);

CREATE TABLE IF NOT EXISTS public."versionamento" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "commits_count" integer DEFAULT 0,
    "version_string" varchar,
    "updated_at" timestamp with time zone DEFAULT now()
);

-- 4. Functions
CREATE OR REPLACE FUNCTION public.handle_new_aluno_wallet()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.tipo_acesso = 'Aluno' THEN
    IF NOT EXISTS (SELECT 1 FROM public."Carteira" WHERE "Usuario" = NEW.id) THEN
      INSERT INTO public."Carteira" ("Usuario", escola_id, "turmaID")
      VALUES (NEW.id, NEW.escola_id, NEW."turmaID");
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.populate_carteira_details()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_turma_id uuid;
  v_escola_id uuid;
BEGIN
  IF NEW."turmaID" IS NULL OR NEW.escola_id IS NULL THEN
    SELECT "turmaID", escola_id
    INTO v_turma_id, v_escola_id
    FROM public.usuarios
    WHERE id = NEW."Usuario";

    IF NEW."turmaID" IS NULL THEN
      NEW."turmaID" := v_turma_id;
    END IF;
    
    IF NEW.escola_id IS NULL THEN
      NEW.escola_id := v_escola_id;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.create_turma(p_escola_id uuid, p_nome text, p_estagio text, p_periodo text, p_serie text, p_professor text, p_quantidade_alunos integer, p_data_entrada date, p_status boolean)
 RETURNS public.turma
 LANGUAGE sql
AS $function$
  INSERT INTO public.turma (
    escola_id,
    nome,
    estagio,
    "Periodos",
    serie,
    professor,
    quantidade_alunos,
    data_entrada,
    status
  ) VALUES (
    p_escola_id,
    p_nome,
    p_estagio,
    p_periodo::public.tipo_periodos,
    p_serie,
    p_professor,
    p_quantidade_alunos,
    p_data_entrada,
    p_status
  )
  RETURNING *;
$function$;

CREATE OR REPLACE FUNCTION public.get_carteiras_by_escola(p_escola_id uuid)
 RETURNS SETOF public."Carteira"
 LANGUAGE sql
 STABLE
AS $function$
  SELECT *
  FROM public."Carteira"
  WHERE escola_id = p_escola_id;
$function$;

CREATE OR REPLACE FUNCTION public.update_turma(p_turma_id uuid, p_nome text, p_estagio text, p_periodo text, p_serie text, p_professor text, p_quantidade_alunos integer, p_data_entrada date, p_status boolean)
 RETURNS public.turma
 LANGUAGE sql
AS $function$
  UPDATE public.turma
  SET
    nome = p_nome,
    estagio = p_estagio,
    "Periodos" = p_periodo::public.tipo_periodos,
    serie = p_serie,
    professor = p_professor,
    quantidade_alunos = p_quantidade_alunos,
    data_entrada = p_data_entrada,
    status = p_status
  WHERE id = p_turma_id
  RETURNING *;
$function$;

CREATE OR REPLACE FUNCTION public.confirmar_investimento_manual(p_investimento_id uuid)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  v_aluno_id uuid;
  v_valor numeric;
  v_status text;
begin
  select aluno_id, valor_investido, status_investimento
  into v_aluno_id, v_valor, v_status
  from investimento_aluno
  where id = p_investimento_id
  for update;

  if not found then
    return json_build_object('success', false, 'message', 'Investimento não encontrado');
  end if;

  if v_status = 'PAGO' then
    return json_build_object('success', false, 'message', 'Este investimento já foi pago');
  end if;

  update investimento_aluno
  set status_investimento = 'PAGO',
      data_inicio = now()
  where id = p_investimento_id;

  update aluno
  set saldo_investido = coalesce(saldo_investido, 0) + v_valor
  where id = v_aluno_id;

  insert into transfeera_log (aluno_id, tipo_operacao, status, response_payload)
  values (v_aluno_id, 'CONFIRMACAO_MANUAL', 'SUCESSO', json_build_object('investimento_id', p_investimento_id, 'valor', v_valor));

  return json_build_object('success', true, 'message', 'Pagamento confirmado e saldo atualizado com sucesso');

exception when others then
  return json_build_object('success', false, 'message', SQLERRM);
end;
$function$;

CREATE OR REPLACE FUNCTION public.increment_app_version()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_commits int;
    v_major int;
    v_minor int;
    v_prefix text;
    v_version_str text;
BEGIN
    SELECT commits_count INTO v_commits FROM versionamento WHERE id = 1;
    IF v_commits IS NULL THEN v_commits := 0; END IF;
    v_commits := v_commits + 1;
    IF v_commits <= 100 THEN
        v_prefix := 'BETA';
        v_major := v_commits / 10;
        v_minor := v_commits % 10;
    ELSE
        v_prefix := 'ALPHA';
        v_major := FLOOR((v_commits - 100) / 10);
        v_minor := (v_commits - 100) % 10;
    END IF;
    v_version_str := v_prefix || ' ' || v_major || '.' || v_minor;
    UPDATE versionamento
    SET commits_count = v_commits,
        version_string = v_version_str,
        updated_at = NOW()
    WHERE id = 1;
    RETURN v_version_str;
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_carteira_code()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.carteira_code IS NULL THEN
    NEW.carteira_code := floor(random() * (99999999 - 10000000 + 1) + 10000000)::text;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user_linking()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public.aluno
  SET user_id = NEW.id
  WHERE email = NEW.email;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_carteira_digital_view(p_escola_id uuid)
 RETURNS TABLE(id bigint, carteira_code character varying, nome_aluno character varying, turma character varying, saldo_atual numeric, status status)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT 
    c.id,
    c.carteira_code,
    u.nome AS nome_aluno,
    t.nome AS turma,
    u.saldo_carteira AS saldo_atual,
    u.status
  FROM public."Carteira" c
  JOIN public.usuarios u ON c."Usuario" = u.id
  LEFT JOIN public.turma t ON u."turmaID" = t.id
  WHERE c.escola_id = p_escola_id;
$function$;

CREATE OR REPLACE FUNCTION public.get_turmas_by_escola(p_escola_id uuid)
 RETURNS TABLE(id uuid, escola_id uuid, nome character varying, ano_semestre character varying, "Periodos" public.tipo_periodos, estagio text, serie text, professor text, quantidade_alunos integer, data_entrada date, status boolean)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT 
    t.id,
    t.escola_id,
    t.nome,
    t.ano_semestre,
    t."Periodos"::public.tipo_periodos,
    t.estagio,
    t.serie,
    t.professor,
    t.quantidade_alunos,
    t.data_entrada,
    t.status
  FROM public.turma t
  WHERE t.escola_id = p_escola_id
  ORDER BY t.nome ASC;
$function$;

CREATE OR REPLACE FUNCTION public.get_turma_balances(p_turma_id uuid)
 RETURNS TABLE(total_saldo_livre numeric, total_saldo_propositos numeric)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT 
    COALESCE(
      (
        SELECT SUM(u.saldo_carteira)
        FROM public.usuarios u
        WHERE u."turmaID" = p_turma_id
      ), 0
    ) AS total_saldo_livre,
    COALESCE(
      (
        SELECT SUM(
          COALESCE(NULLIF(regexp_replace(p.saldo, '[^0-9.]', '', 'g'), ''), '0')::numeric
        )
        FROM public.propositos p
        JOIN public.usuarios u ON p.usuario_id = u."UserID" 
        WHERE u."turmaID" = p_turma_id
      ), 0
    ) AS total_saldo_propositos;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_usuario_propositos()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  PERFORM extensions.http_post(
    url := 'https://xlupnknqblvvlcfprghr.supabase.co/functions/v1/create-user-propositos',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key', true)
    ),
    body := jsonb_build_object('record', row_to_json(NEW))
  );
  RETURN NEW;
END;
$function$;

-- 5. Triggers
CREATE TRIGGER trg_auto_create_aluno_wallet
AFTER INSERT ON public.usuarios
FOR EACH ROW EXECUTE FUNCTION public.handle_new_aluno_wallet();

CREATE TRIGGER on_usuario_created
AFTER INSERT ON public.usuarios
FOR EACH ROW EXECUTE FUNCTION public.handle_new_usuario_propositos();

CREATE TRIGGER trg_check_carteira_details
BEFORE INSERT ON public."Carteira"
FOR EACH ROW EXECUTE FUNCTION public.populate_carteira_details();

CREATE TRIGGER trg_generate_carteira_code
BEFORE INSERT ON public."Carteira"
FOR EACH ROW EXECUTE FUNCTION public.generate_carteira_code();

-- 6. RLS Policies
ALTER TABLE public.whatsapp_instances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can delete own instance" ON public.whatsapp_instances FOR DELETE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own instance" ON public.whatsapp_instances FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own instance" ON public.whatsapp_instances FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can view own instance" ON public.whatsapp_instances FOR SELECT TO public USING (auth.uid() = user_id);

ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can delete own messages" ON public.whatsapp_messages FOR DELETE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own messages" ON public.whatsapp_messages FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own messages" ON public.whatsapp_messages FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can view own messages" ON public.whatsapp_messages FOR SELECT TO public USING (auth.uid() = user_id);

ALTER TABLE public.propositos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Policy with security definer functions" ON public.propositos FOR ALL TO public USING (true);

ALTER TABLE public."Carteira" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "DouglasDev" ON public."Carteira" FOR ALL TO public USING (true);

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir Insercao Publica Usuarios" ON public.usuarios FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Permitir Leitura Publica Usuarios" ON public.usuarios FOR SELECT TO anon, authenticated USING (true);

ALTER TABLE public.pedidos_compra ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for pedidos_compra" ON public.pedidos_compra FOR ALL TO public USING (true);

ALTER TABLE public.pedidos_compra_itens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for pedidos_compra_itens" ON public.pedidos_compra_itens FOR ALL TO public USING (true);
